### PR TITLE
WI-2246 Restricted lo-dash to versions 3.x. Some methods of version >…

### PR DESCRIPTION
**Pull request by EoinGriffin-AI**
…=4.x (e.g. _.rest) are not backwards compatible.

Logger will log a console error if string formatting fails. This can happen if there's a % in log message.

@JesseChezenko-AI This fixes an issue where the string formatting method can fail if there's a % in the string. For example, the situation I encountered was a Unit in AQ Samples with a customId of "%REC". This gets interpreted by _.sprintf() as a replacement token, which then throws a very unhelpful message "`Error: [_.sprintf] huh?`"

### CODE REVIEW

**Comment by JesseChezenko-AI** [comment]
lgtm..

could you run the build script to build the dist/ai-logger.js and add that to this PR?

**Comment by EoinGriffin-AI** [comment]
@JesseChezenko-AI Build files have been committed.

**Comment by JesseChezenko-AI** [comment]
thanks!

**Comment by SimonNodel-AI** [comment]
Thanks for doing this Eoin.  However, you may want to consider different approach for example re-factor the code to remove dependency on incompatible lodash functions so you can keep compatibility with lodash 4.

**Pull request merged**
